[supabase]
url = "https://mfuceucqjgyarlbbkgvv.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1mdWNldWNxamd5YXJsYmJrZ3Z2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjUyMDk2NTIsImV4cCI6MjA4MDc4NTY1Mn0.34QdEvpitjx3rwLmBt6eB0-bPVxuKVcnnU29AyH4N50"